# --------------------------
# Rendezvous config file
# --------------------------
ServerMode: false
Verbose: true

ClientConfig:
  - TargetAddress: 172.27.26.164
    Ports:
      - 7050
      - 7051
      - 7052
    ProbeServerRunning: true

    # Next options have meaning only when ProbeServerRunning is true
    CheckDockerImages:
      - hyperledger/fabric-ccenv:latest:5b31d55f5f3a
      - hyperledger/fabric-tools:1.4.0:0a44f4261a55
      - hyperledger/fabric-orderer:1.4.0:54f372205580
      - hyperledger/fabric-peer:1.4.0:304fac59b501
      - hyperledger/fabric-baseos:amd64-0.4.14:75f5fb1a0e0c
    ListDockerImages: false
    
  - TargetAddress: 172.27.26.82
    Ports:
      - 7050
      - 7051
      - 7052
    ProbeServerRunning: true

    # Next options have meaning only when ProbeServerRunning is true
    CheckDockerImages:
      - hyperledger/fabric-ccenv:latest:5b31d55f5f3a
      - hyperledger/fabric-tools:1.4.0:0a44f4261a55
      - hyperledger/fabric-orderer:1.4.0:54f372205580
      - hyperledger/fabric-peer:1.4.0:304fac59b501
      - hyperledger/fabric-baseos:amd64-0.4.14:75f5fb1a0e0c
    ListDockerImages: false
